/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.3.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.spotless)

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

dependencies {
    implementation(libs.arrow.core)
    implementation(libs.arrow.fx.coroutines)
    implementation(libs.bifurcan)
    implementation(libs.playwright)
    implementation(libs.typesafe.config)
    implementation(libs.kotlin.logging)
    implementation(libs.kotlinx.serialization.json)

    // Kotest
    testImplementation(libs.kotest.runner.junit5)
    testImplementation(libs.kotest.assertions.core)
    testImplementation(libs.kotest.assertions.arrow)

    // JUnit 5 (for extensions and integration tests)
    testImplementation(platform(libs.junit.bom))
    testImplementation(libs.junit.jupiter)
    testImplementation(libs.junit.platform.launcher)
    testImplementation(libs.assertk)
    testImplementation(libs.logback.classic)

    // Database (test statistics)
    testImplementation(libs.turso)
    testImplementation(libs.flyway.core)
    testImplementation(libs.sqlite.jdbc)

    // AWS (Java SDK for testcontainers interop)
    testImplementation(platform(libs.aws.bom))
    testImplementation(libs.aws.secretsmanager)

    // Testcontainers
    testImplementation(platform(libs.testcontainers.bom))
    testImplementation(libs.testcontainers.localstack)
    testImplementation(libs.testcontainers.junit.jupiter)

    // This dependency is used by the application.
    implementation(libs.guava)
}

kotlin {
    jvmToolchain(25)
    compilerOptions {
        freeCompilerArgs.add("-Xcontext-parameters")
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    withSourcesJar()
}

application {
    // Define the main class for the application.
    mainClass = "oscarvarto.mx.perf.BifurcanExercisesKt"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
    jvmArgs("--enable-native-access=ALL-UNNAMED")
}

spotless {
    format("misc") {
        target(".gitattributes", ".gitignore")
        trimTrailingWhitespace()
        endWithNewline()
        leadingSpacesToTabs(2)
    }
    kotlin {
        target("src/**/*.kt")
        ktlint()
    }
    kotlinGradle {
        target("**/*.gradle.kts")
        ktlint()
    }
}

tasks.register<JavaExec>("playwrightCli") {
    group = "playwright"
    description = "Runs the Playwright CLI. Pass commands via --args, e.g. --args=\"codegen https://example.com\""
    classpath = sourceSets["main"].runtimeClasspath
    mainClass.set("com.microsoft.playwright.CLI")
}
